--- #YAML:1.0
name:                POE-Loop-Glib
version:             0.0033
abstract:            a bridge that supports Glib's event loop from POE
license:             GPL
author:              
    - Martijn van Beers  <martijn@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Glib:                          0
    POE:                           0.30
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
