---
abstract: 'a bridge that supports Glib''s event loop from POE'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 1.00
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Loop-Glib
no_index:
  directory:
    - inc
    - t
requires:
  Glib: 1.181
  POE: 1.0
tests: 't/*.t t/Glib/*.t'
version: 0.0034
