---
abstract: 'a bridge that supports Glib''s event loop from POE'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  POE::Test::Loops: 1.001
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Loop-Glib
no_index:
  directory:
    - inc
    - t
provides:
  POE::Loop::Glib:
    file: lib/POE/Loop/Glib.pm
recommends:
  IO::Pty: 0
  Socket6: 0
  Term::Readkey: 0
  Win32::Console: 0
requires:
  Glib: 1.181
  POE: 1.0
  perl: 5.6.0
version: 0.0035
